Venevolenze/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'app'
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('sample/', views.sample, name='sample'),
    path('sample_new', views.sample_new, name='sample_new'),
    path('book/<int:book_id>/', views.consideration, name='consideration'),  # detail
    path('book/<str:category>/', views.books_category, name='books_category'),  # category
    path('new_book_consider/', views.new_book_consider, name='new_book_consider'),  # new
    path('delete/<int:book_id>/', views.delete, name='delete'),  # delete
    path('edit/<int:book_id>/', views.edit, name='edit'),  # edit
]

Venevolenze/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

Venevolenze/app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator


class Category(models.Model):
    """カテゴリー"""
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class ReadBook(models.Model):
    """読んだ本"""
    title = models.CharField(blank=False, null=False, max_length=40)
    quote1 = models.TextField(blank=True)
    consideration1 = models.TextField(blank=True)
    quote2 = models.TextField(blank=True)
    consideration2 = models.TextField(blank=True)
    quote3 = models.TextField(blank=True)
    consideration3 = models.TextField(blank=True)
    consideration4 = models.TextField(blank=False, null=False, validators=[MinLengthValidator(50)])
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

Venevolenze/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):
    """カスタムユーザーマネジャー"""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """emailを必須にする"""
        if not email:
            raise ValueError('正しいメールアドレスを入力してください')

        """emailでUserモデルを作成"""
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('管理者権限は、スタッフ(is_staff)でなければなりません')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('管理者権限は、管理者(is_superuser)でなければなりません')
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('管理者権限は、スタッフ(is_staff)でなければなりません')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('管理者権限は、管理者(is_superuser)でなければなりません')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル"""
    email = models.EmailField("メールアドレス", unique=True)
    is_staff = models.BooleanField("is_staff", default=False)
    is_active = models.BooleanField("is_active", default=True)
    date_joined = models.DateTimeField("date_joined", default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

Venevolenze/app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from django.forms import ModelForm
from .models import ReadBook

from django import forms


class ReadBookForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '入力必須(40文字以下)'
    }))

    consideration4 = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': '入力必須、50文字以上入力してください。'})
    )

    class Meta:
        model = ReadBook
        fields = [
            'title',
            'quote1', 'consideration1',
            'quote2', 'consideration2',
            'quote3', 'consideration3',
            'consideration4', 'category',
        ]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email',)

Venevolenze/app/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm
from .models import ReadBook, Category
from .forms import ReadBookForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model


@login_required(login_url='/login/')
def index(request):
    users = get_user_model().objects.all()
    books = ReadBook.objects.filter(user=request.user).order_by('-id')
    return render(request, 'app/index.html', {'books': books, 'users': users})


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_email = form.cleaned_data['email']
            input_password = form.cleaned_data['password1']
            new_user = authenticate(email=input_email, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('app:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'app/signup.html', {'form': form})


def sample(request):
    return render(request, 'app/sample.html')


def sample_new(request):
    return render(request, 'app/sample_new.html')


@login_required(login_url='/login/')
def consideration(request, book_id):
    login_user = get_user_model().id
    book = get_object_or_404(ReadBook, pk=book_id)
    if request.user == book.user:
        context = {
            'book': book,
        }
        return render(request, 'app/consideration.html', context)
    return redirect('app:index')


@login_required(login_url='/login/')
def new_book_consider(request):
    if request.method == "POST":
        form = ReadBookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user
            book.save()
            messages.success(request, "新しく追加できました。")
        return redirect('app:index')
    else:
        form = ReadBookForm
    return render(request, 'app/new_book_consider.html', {'form': form})


@login_required(login_url='/login/')
@require_POST
def delete(request, book_id):
    book = get_object_or_404(ReadBook, id=book_id)
    book.delete()
    return redirect('app:index')


@login_required(login_url='/login/')
def edit(request, book_id):
    book = get_object_or_404(ReadBook, id=book_id)

    if request.user == book.user:
        if request.method == "POST":
            form = ReadBookForm(request.POST, instance=book)
            if form.is_valid():
                form.save()
                return redirect('app:consideration', book_id=book_id)
        else:
            form = ReadBookForm(instance=book)
        return render(request, 'app/edit.html', {'form': form, 'book': book})
    else:
        return redirect('app:index')


@login_required(login_url='/login/')
def books_category(request, category):
    category = Category.objects.get(title=category)
    books = ReadBook.objects.filter(category=category, user=request.user).order_by('-created_at')
    return render(request, 'app/index.html', {'books': books, 'category': category})

Venevolenze/users/views.py
from django.shortcuts import render

# Create your views here.

Venevolenze/app/templates/app/base.html
<!DOCTYPE html >
<html>
<head>
    {% load static %}
    <title>Venevolenze</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>
<header>
    <div class="container">
        <h1><a href="{% url 'app:index' %}">Venevolenze</a></h1>
        <div class="header-menu">
            {% if request.user.is_authenticated %}
                <!-- ここにあとで[お気に入りの文]を追加 -->
                <a href="{% url 'app:logout' %}">ログアウト</a>
            {% else %}
                <a href="{% url 'app:login' %}">ログイン</a>
                <a href="{% url 'app:signup' %}">新規登録</a>
            {% endif %}
        </div>
    </div>
</header>
<div class="container">
    {% for message in messages %}
        <p class="message-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
    {% block content %} {% endblock %}
</div>
</body>
</html>

Venevolenze/app/templates/app/consideration.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>本について</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/consideration.css' %}">
</head>

<body>
    <div class="consideration-wrapper">
        <div class="column left-bar">
            <div class="left-category-container">
                <ul>
                    <li class="list-index">

                    </li>
                </ul>
            </div>
        </div>
        <div class="column left-bar-pretend">
            <div class="left-category-container-pretend">

            </div>
        </div>
        <div class="column right-consideration">
            <div class="right-category-container">
                <header>
                    <h3 class="box-a-back">
                        <a href="{% url 'app:index' %}" class="a-back-to-index">＜</a>
                    </h3>
                </header>
                {% if request.user == book.user %}
                <section class="each-book-consideration-wrapper">
                    <table>
                        <tr>
                            <td class="title">
                                <h3>{{ book.title }}</h3>
                            </td>
                            <td class="title-backspace"></td>
                            <td class="book">
                                <h1 class="book-title">{{ book.title }}</h1>
                                <hr class="book-title-hr" color="#6c272d" />

                                {% if book.quote1 %}
                                    <blockquote>
                                        <p class="p-quotes">
                                            <span class="double-quot">“</span>
                                            <br>
                                                {{ book.quote1 }}
                                            <br>
                                        </p>
                                    </blockquote>
                                {% endif %}

                                {% if book.consideration1 %}
                                    <p class="p-considerations">{{ book.consideration1 }}</p>
                                    <hr class="book-title-hr" color="#6c272d" />
                                {% endif %}

                                {% if book.quote2 %}
                                    <blockquote>
                                        <p class="p-quotes">
                                            <span class="double-quot">“</span>
                                            <br>
                                                {{ book.quote2 }}
                                        </p>
                                    </blockquote>
                                {% endif %}

                                {% if book.consideration2 %}
                                    <p class="p-considerations">{{ book.consideration2 }}</p>
                                    <hr class="book-title-hr" color="#6c272d" />
                                {% endif %}

                                {% if book.quote3 %}
                                    <blockquote>
                                        <p class="p-quotes">
                                            <span class="double-quot">“</span>
                                            <br>
                                            {{ book.quote3 }}
                                        </p>
                                    </blockquote>
                                {% endif %}

                                {% if book.consideration3 %}
                                    <p class="p-considerations">{{ book.consideration3 }}</p>
                                    <hr class="book-title-hr" color="#6c272d" />
                                {% endif %}

                                <p class="p-considerations">{{ book.consideration4 }}</p>
                                <hr class="last-book-title-hr" color="#6c272d" />
                                <br>
                                <div class="category-datetime">
                                    <span class="span-category">
                                        {{ book.category }}
                                    </span><br>
                                    <p class="p-created_datetime">{{ book.created_at }}</p>

                                    {% if updated_at %}
                                    {{ book.updated_at }}
                                    {% endif %}
                                </div>
                                <br>
                            </td>
                        </tr>
                    </table>
                </section>
                {% else %}
                    <p>あなたはログインしてません</p>
                {% endif %}

                <div class="button-container">
                    <div class="book-edit-and-delete">
                        {% if request.user == book.user %}
                            <a href="{% url 'app:edit' book.id %}"><button class="btn-edit">編集</button></a>
                            <form action="{% url 'app:delete' book.pk %}" method="post">{% csrf_token %}
                                <button class="btn-delete" type="submit" onclick='return confirm("本当に削除しますか");'>
                                    削除
                                </button>
                            </form>
                        {% else %}
                            <!-- <a href="{% url 'app:login' %}"><button class="btn-edit">編集</button></a>
                            <form action="{% url 'app:login' %}" method="post">{% csrf_token %}
                                <button class="btn-delete" type="submit" onclick='return confirm("本当に削除しますか");'>
                                    削除
                                </button>
                            </form> -->
                        {% endif %}
                    </div>
                    <div class="div-a-to-index">
                        <a href="{% url 'app:index' %}" class="a-to-index">トップページ戻る</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Venevolenze/app/templates/app/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>マイブック</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
</head>

<body>
    <div class="wrapper">
        <div class="column left-bar">
            <div class="left-category-container">
                <ul>
                    <li class="list-index"></li>
                </ul>
            </div>
        </div>
        <div class="column left-bar-pretend">
            <div class="left-category-container-pretend">

            </div>
        </div>

        <div class="column right-bar">
            <div class="right-category-book-container">
                <header>
                    <h6 class="linkToCreate">
                        <div class="header-menu">
                            {% if request.user.is_authenticated %}
                            <!-- ここにあとで[お気に入りの文]を追加 -->
                            <a href="{% url 'app:logout' %}" class="a-logout">ログアウト</a> /
                            {% endif %}
                            <a href="{% url 'app:new_book_consider'%}" class="a-create">
                                本追加
                            </a>
                        </div>
                    </h6>
                    <h1 style="color: #afafb0;">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'app:index' %}" class="service-name">Venevolenze</a>
                        {% else %}
                            <a href="{% url 'app:login' %}" class="service-name">Venevolenze</a>
                        {% endif %}
                    </h1>
                </header>
                <hr color="#6c272d" />
                    {% for message in messages %}
                    <p class="message-{{ message.tags }}">{{ message }}</p>
                    {% endfor %}


                    <section class="each-book-wrapper">
                        <p>{{user}}</p>
                        {% if request.user.is_authenticated %}
                            {% for book in books %}
                                <table>
                                    <tr>
                                        <td class="title">
                                            <a href="{% url 'app:consideration' book_id=book.id %}" class="a-title">
                                                {{ book.title }}
                                            </a>
                                        </td>
                                        <td class="book-category">
                                            <cite class="b-c-box">
                                                <a href="{% url 'app:books_category' category=book.category %}" class="a-category">{{ book.category }}</a>
                                            </cite>
                                        </td>
                                        <td class="consideration4">
                                            <a href="{% url 'app:consideration' book_id=book.id %}">
                                                {{ book.consideration4 }}
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            {% endfor %}
                        {% else %}
                            <p>あなたはログインしていません</p>
                        {% endif %}
                    </section>

            </div>
        </div>
    </div>
</body>
</html>

Venevolenze/app/templates/app/login.html
<!DOCTYPE html >
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    {% load static %}
    <title>Venevolenze</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>
<header>
    <div class="container">
        {% if request.user.is_authenticated %}
            <h1><a href="{% url 'app:index' %}">Venevolenze</a></h1>
        {% else %}
            <h1><a href="{% url 'app:login' %}">Venevolenze</a></h1>
        {% endif %}

    </div>
</header>
<div class="wrapper">
    <div class="column left">
        <h1 class="explanation">
            <span class="span-only-you">本の内容を整理するのに</span> <br>
            <br>
            使ってみてください<br>
        </h1>
        <p class="to-sample"><a href="{% url 'app:sample' %}">サンプルをみる</a></p>
    </div>
    <div class="column right">
        <div class="right-container">

            <form class="form-sign" method="post">{% csrf_token %}
                {% if form.errors %}
                    <p>メールアドレスかパスワードが間違っています。</p>
                {% endif %}

                <h2>ログイン</h2>
                <div class="label-email">
                    <label>メールアドレス</label>
                    <br>
                    <input name="username" required>
                </div>
                <div class="label-password">
                    <label>パスワード</label>
                    <br>
                    <input name="password" required>
                </div>
                <input type="submit" value="ログイン" class="login">
            </form>

            <!-- {% if request.user.is_authenticated is not True %}
            <div  class="a-signup">
                <a href="{% url 'app:signup' %}">新規登録はこちら</a>
            </div>
            {% endif %} -->

            <div  class="a-signup">
                <a href="{% url 'app:signup' %}">新規登録はこちら</a>
            </div>


            <p class="to-sample-for-smartphone"><a href="{% url 'app:sample' %}">トップページと本追加ページをみる</a></p>
        </div>
    </div>
</div>
</body>
</html>

Venevolenze/app/templates/app/sample.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>サンプル</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/sample.css'%}">
</head>

<body>
    <div class="wrapper">
        <div class="column left-bar">
            <div class="left-category-container">
                <ul>
                    <li class="list-index"></li>
                </ul>
            </div>
        </div>
        <div class="column left-bar-pretend">
            <div class="left-category-container-pretend">

            </div>
        </div>
        <div class="column right-bar">
            <div class="right-category-book-container">
                <header>
                    <h6 class="linkToCreate">
                        <a href="{% url 'app:sample_new'%}" class="a-create">
                            本追加
                        </a>
                    </h6>
                    <h1 style="color: #afafb0;">
                        <a href="{% url 'app:sample' %}" class="service-name">Venevolenze</a>
                    </h1>
                </header>
                <hr color="#6c272d" />
                <section class="each-book-wrapper">
                        <table>
                            <tr>
                                <td class="title">
                                    <a class="a-title">
                                        本のタイトル
                                    </a>
                                </td>
                                <td class="book-category">
                                    <cite class="b-c-box">
                                        <a class="a-category">
                                            カテゴリー
                                        </a>
                                    </cite>
                                </td>
                                <td class="consideration4">
                                    <a>
                                        本の内容、自分で考えたことをここに書くことができます。<br>
                                        今回はサンプルなので省略します。
                                        また本の内容を忘れたときに大事な部分だけを見直すことができます。
                                    </a>
                                </td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td class="title">
                                    <a class="a-title">
                                        本のタイトル
                                    </a>
                                </td>
                                <td class="book-category">
                                    <cite class="b-c-box">
                                        <a class="a-category">
                                            カテゴリー
                                        </a>
                                    </cite>
                                </td>
                                <td class="consideration4">
                                    <a>
                                        本の内容、自分で考えたことをここに書くことができます。<br>
                                        今回はサンプルなので省略します。
                                        また本の内容を忘れたときに大事な部分だけを見直すことができます。
                                    </a>
                                </td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td class="title">
                                    <a class="a-title">
                                        本のタイトル
                                    </a>
                                </td>
                                <td class="book-category">
                                    <cite class="b-c-box">
                                        <a class="a-category">
                                            カテゴリー
                                        </a>
                                    </cite>
                                </td>
                                <td class="consideration4">
                                    <a>
                                        本の内容、自分で考えたことをここに書くことができます。<br>
                                        今回はサンプルなので省略します。
                                        また本の内容を忘れたときに大事な部分だけを見直すことができます。
                                    </a>
                                </td>
                            </tr>
                        </table>
                            <tr>
                                <td>
                                    <p class="sample-to-signup"><a href="{% url 'app:signup' %}">新規登録画面に戻る</a></p>
                                </td>
                            </tr>
                        </table>
                </section>
            </div>
        </div>
    </div>
</body>
</html>

Venevolenze/app/templates/app/signup.html
<!DOCTYPE html >
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    {% load static %}
    <title>Venevolenze</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>
<header>
    <div class="container">
        <h1><a href="{% url 'app:index' %}">Venevolenze</a></h1>
    </div>
</header>
<div class="wrapper">
    <div class="column left">
        <h1 class="explanation">
            <span class="span-only-you">本の内容を整理するのに</span> <br>
            <br>
            使ってみてください<br>
        </h1>
        <p class="to-sample"><a href="{% url 'app:sample' %}">サンプルをみる</a></p>
    </div>
    <div class="column right">
        <div class="right-container">
            {% for message in messages %}
                <p class="message-{{ message.tags }}">{{ message }}</p>
            {% endfor %}
            <h2>ユーザー登録</h2>
            <form method="post" action="{% url 'app:signup' %}">{% csrf_token %}
                <div class="signup-label-email">
                    <label>メールアドレス</label>
                    <br>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <br>
                <div class="signup-label-password">
                    <label>パスワード</label>
                    <br>
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                </div>
                <br>
                <div class="signup-label-password">
                    <label>パスワード(確認)</label>
                    <br>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                </div>
                <br>
                <input type="submit" value="登録する">
            </form>

            <div  class="a-login">
                <a href="{% url 'app:login' %}">ログインはこちら</a>
            </div>

            <p class="to-sample-for-smartphone"><a href="{% url 'app:sample' %}">Venevolenzeのサンプルをみる</a></p>
        </div>
    </div>
</div>
</body>
</html>